dbs:
  - path: /var/lib/headscale/db.sqlite
    replicas:
      - type: s3
        bucket: ${LITESTREAM_S3_BUCKET}
        path: ${LITESTREAM_S3_PATH}
        region: ${AWS_REGION}
        sync-interval: 30s
